version: '3.9'
services:
  backend:
    container_name: urlsshortener_backend
    build: ./backend
    ports:
      - "5000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=urlsshortener_db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_NAME=urlsshortenerdb
      - BASE_URL=http://localhost:5000

  frontend:
    container_name: urlsshortener_frontend
    build: ./frontend
    ports:
      - "5001:5173"
    environment:
      - VITE_BACKEND_BASE_URL=http://backend:5000
  
  db:
    container_name: urlsshortener_db
    image: postgres:13
    ports:
      - "5002:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=urlsshortenerdb